import 'package:flutter/material.dart';

const kPrimaryColor = Color(0xFF27aae1);
const kGoGame = 'Go Game';
const kRows = 'Game Name A';
const kColumns = 'Columns';
const kTextImage = 'Text & Image';
const kDataBase = 'Database';
const kRow1 = 'Row 1';
const kRow2 = 'Row 2';
const kRow3 = 'Row 3';
const kColumn1 = 'Column 1';
const kColumn2 = 'Column 2';
const kColumn3 = 'Column 3';
const kPrev = 'Prev';
const kNext = 'Next';
const kSave = 'Save';
const kAddPicture = 'Add Picture';
const kContact = 'Contact';
const kEmail = 'Email';
const kMobile = 'Mobile';
const kName = 'Name';
const kAddImage = 'Add Image';
const kCamera = 'Camera';
const kGallery = 'Gallery';
const kDelete = 'Delete';
const kUndo = 'Undo';
